### PR TITLE
Socket identification

### PR DESCRIPTION
**Pull request by ZynoXelek**
Relates to #18.
Stop storing ip in the players and use generated sockets to identify them instead.
Also add better try/except tests and fix some minor bugs.

### CODE REVIEW

**Comment by ZynoXelek** [comment]
@BlueNZ I'll let you resolve the conflict as it concerns the interpreter. The simple objective is to adapt it as ip is not in the structure player anymore.
I guess the if statement should be kept and the single thing to do would be to implement the new line of code inside of it instead of the old one but I'll let you manage it as I'm not sure.

**Review by BlueNZ — APPROVED** [review]
We may need to print less to not overflow the console command

**Review by Laudut — APPROVED** [review]

**Review by BlueNZ — APPROVED** [review]
works

**Review by Shisohka — APPROVED** [review]
Nice !

**Pull request merged**
